/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    FooterMain: typeof import('./src/components/layout/FooterMain.vue')['default']
    HeaderMain: typeof import('./src/components/layout/HeaderMain.vue')['default']
    Image: typeof import('primevue/image')['default']
    LayoutMain: typeof import('./src/components/layout/LayoutMain.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
  }
}
